### ISSUE TITLE
redirect problem

### ISSUE THREAD

**Issue by towncraftserver** [ruany/litebans-php#22] opened 2017-07-20 06:45 UTC
in my settings I typed as follows

      // Clicking on the header name will send you to this address.
        $this->name_link = 'www.mydomain.com';
Save
Go back to the bans page. When I click on my servers name in the top left it then takes me to the page
www.mydomain.com/bans/www.mydomain.com
Which clearly isn't a page, and I get an Error message on my page.

**Comment by ruany** [comment] 2017-07-20 06:48
You haven't specified a full URL so it will use a relative URL.

Full URL example:
```
        $this->name_link = 'http://www.google.com';
```

Closing, not a bug.

**Closed by ruany** 2017-07-20 06:48 UTC

**Comment by towncraftserver** [comment] 2017-07-20 07:15
Ah gotcha.
Okay thank you very much. I will try that!
