### ISSUE TITLE
Can't figure out how to set it up

### ISSUE THREAD

**Issue by drugislandserver** [ruany/litebans-php#1] opened 2016-01-05 01:41 UTC
I have absolutely no idea how to set up this page, I've tried a ton of different things, but none of them work, are there any tutorials on how to set this up?

**Comment by ruany** [comment] 2016-01-05 14:00
1. Download the ZIP archive
2. Extract it to the PHP web server's root directory
3. Edit includes/settings.php

There are no tutorials because uploading files isn't really a hard task, and there are hundreds of different ways to upload files.

I'm closing this since it's not a bug, everyone else who has successfully installed it thus far has done it by looking at these steps.

If you could mention what you're trying to host it on and what you've tried so far, I would have something else to say.

**Closed by ruany** 2016-01-05 14:00 UTC
