### ISSUE TITLE
I get this is response when I go onto my website:

### ISSUE THREAD

**Issue by upsemand** [ruany/litebans-php#16] opened 2017-01-04 18:08 UTC
Error: date_format test failed. strftime("%B %D, %Y, %R",0) returned bool(false) Assertion failed: strftime("%F %T",0) != "1970-01-01 00:00:00"
Actual result: bool(false)

**Comment by ruany** [comment] 2017-01-04 18:17
I've never experienced this error myself and I've seen many working installations so this seems like a rare bug.

I'll need much, much more information to attempt to fix it though. System information, PHP version, and web server error logs might help.

**Comment by upsemand** [comment] 2017-01-04 18:27
Fairly simple, using the latest version of XAMPP, with everything standard, ofcorse toggled MYSQL features in php.ini.

I don't get any errors other then the one showing on the page.

**Comment by upsemand** [comment] 2017-01-04 19:34
Windows Server 2012 R2

**Comment by ruany** [comment] 2017-01-04 19:39
I don't have a Windows machine to test with, so there's unfortunately nothing I can do to pinpoint the problem without additional information about the bug at this stage.

**Comment by SilentX88** [comment] 2017-01-08 05:38
I  got that error on my linux server when try to change from date_default_timezone_set("UTC"); 
to my local timezone date_default_timezone_set("Europe/Belgrade");

see this: https://secure.php.net/manual/en/function.strftime.php

**Comment by ruany** [comment] 2017-01-08 06:23
Should be fixed by https://github.com/ruany/litebans-php/commit/e60cefc43b7aa054ea430595e26e6dc7dc8b136d

**Comment by ruany** [comment] 2017-02-03 11:38
Might be fixed by https://github.com/ruany/litebans-php/commit/ea2596500368189761fefa0e5f7147a10e42ae2d
Since I still can't reproduce the bug, I'm closing the issue in hopes that it is actually fixed.
Issue can be re-opened if it still occurs.

**Closed by ruany** 2017-02-03 11:38 UTC
Labels: Can't reproduce, help wanted
